# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0586c56c3dddb866fedee274086735cfb94ee1a0938c64388f939f449de6d14cf7b696218a134f76ab7c68f20cefc7cfc5c22cc538e3f165de96d5883f33b323

test:
  secret_key_base: 102fb27bee6a495458c61ec7f9c8c3bc9e88cb78e511aa68c050c74d781a5bbb528f84c196c3e51a430c1ae8387ea00b92e8c742b83b163288f9b80a1741a4d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
